#prettier-ignore
version: "3"
services:
  frontend:
    build: ./frontend/
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - authentication
      - courses
      - payment
      - enrollment

  authentication:
    build: ./service-user-management/
    ports: 
      - "4000:4000"
    volumes: 
      - ./service-user-management/:/app
      - /app/node_modules
    env_file:
      - ./service-user-management/.env

  enrollment:
    build: ./service-learner-enrollment/
    ports: 
      - "4001:4001"
    volumes: 
      - ./service-learner-enrollment/:/app
      - /app/node_modules
    env_file:
      - ./service-learner-enrollment/.env

  courses:
    build: ./service-course-management/
    ports: 
      - "3500:3500"
    volumes: 
      - ./service-course-management/:/app
      - /app/node_modules
    env_file:
      - ./service-course-management/.env

  payment:
    build: ./service-payment-management/
    ports: 
      - "4002:4002"
    volumes: 
      - ./service-payment-management/:/app
      - /app/node_modules
    env_file:
      - ./service-payment-management/.env
